apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: $CI_REGISTRY_IMAGE/wordpress:latest
        ports:
          - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            value: "mysql-service"       # Update with your MySQL service name
          - name: WORDPRESS_DB_NAME
            value: "wordpress"
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: wordpress-db-secret
                key: username             # Username stored in Kubernetes Secret
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wordpress-db-secret
                key: password             # Password stored in Kubernetes Secret
        volumeMounts:
          - name: wordpress-persistent-storage
            mountPath: /var/www/html/wp-content  # Persistent storage for /wp-content
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc        # Persistent Volume Claim for /wp-content

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wordpress
